### ISSUE TITLE
Communication 

### ISSUE THREAD

**Issue by rajanpaul02-zz** [PyMoDAQ/pymodaq_plugins_newport#1]
Hi,
The code runs fine in my python platform. Kindly could you let me know how to install it properly and run commands to the conex agap motor controller?

Thanks 
Rajan

**Comment by rajanpaul02** [comment]
Hi @seb5g 
I am trying to connect my Conex agap ag m100d, motorized mirror mount via python. I installed this package still, I am unable to construct the main function wherein I can command the mirror or establish communication with it. Kindly could you let me know how to do it or share an example of the file to send commands to the motor?
Thanks
Rajan

**Comment by seb5g** [comment]
Well you have to install the driver from newport and let the daq_move module know where to look for the conex library default is: 
``conex_path='C:\\Program Files\\Newport\\Piezo Motion Control\\Newport CONEX-AGAP Applet\\Samples'``
Then you should be able to use it with the DAQ_Move module interface

**Comment by rajanpaul02** [comment]
Hi @seb5g , thanks for the response! I have mentioned the path in DAQ_Move conex. 
Where can I find the  DAQ_Move module interface?

Thanks
Rajan

**Comment by seb5g** [comment]
https://pymodaq.cnrs.fr/en/latest/usage/How_to_start.html

**Comment by rajanpaul02** [comment]
Hi, I am running the python -m pymodaq.daq_move.daq_move_main from my venv. 
Getting this error : QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)"
Could you suggest something to fix?

Thanks
Rajan

**Comment by seb5g** [comment]
seems so be an issue with Qt5 QWindows but difficult to say more. I usually start pymodaq from a dedicated conda env where python version can be tailored while venv use one installed python version...

**Comment by rajanpaul02** [comment]
Hi @seb5g , thanks for helping with this! I am running the form test with actuator Conex, getting the error: The parameter is incorrect. any suggestions regarding this?

Thanks
Rajan
